version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres-plw-db
    restart: always
    environment:
      POSTGRES_DB: braincomua_plw_db
      POSTGRES_USER: admin1
      POSTGRES_PASSWORD: admin1
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: